version: '3.8'

services:
  db:
    image: mcr.microsoft.com/mssql/server:2022-latest
    container_name: qure-sql-server
    ports:
      - "1433:1433"
    environment:
      - ACCEPT_EULA=Y
      - MSSQL_SA_PASSWORD=VibeQ@123_SecurePassword # Must be strong
      - MSSQL_PID=Developer
    volumes:
      - sql-data:/var/opt/mssql
    restart: always

  qure-app:
    build: .
    container_name: qure-hospital-hub
    depends_on:
      - db
    ports:
      - "3010:3000"
    restart: always
    environment:
      - NODE_ENV=production
      - QUEUE_DB_USER=sa
      - QUEUE_DB_PASSWORD=VibeQ@123_SecurePassword
      - QUEUE_DB_SERVER=db  # Connects to the 'db' service container
      - QUEUE_DB_NAME=HospitalQueueDB
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "3"

volumes:
  sql-data:

